bot:
  token: ${BOT_TOKEN}
  username: abylalkhan_bot
  admin-users: ${BOT_ADMIN_USERS}
  secret-users: ${BOT_SECRET_USERS}
  admin-password: ${BOT_ADMIN_PASSWORD}
  forward-group-id: ${FORWARD_GROUP_ID}
  cat-service-url: ${CAT_SERVICE_URL}

aws:
  s3:
    bucket: abylalkhan-telegram-bot
    region: eu-north-1
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

spring:
  application:
    name: bot
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true